version: '3.7'
services: 
  mysql:
    image: yukitoki/mariadb:10.4
    container_name: wp-mariadb
    volumes: 
        - mariadb:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    networks: 
        - wp_network
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    container_name: wp-wordpress
    volumes: 
        - wordpress:/var/www/html
    depends_on: 
        - mysql
    environment: 
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always
    networks: 
        - wp_network
  nginx: 
    image: yukitoki/nginx-alpine-ssl
    container_name: wp-nginx
    volumes: 
        - wordpress:/var/www/html
        - $PWD/conf.d:/etc/nginx/conf.d
        - $PWD/ssl:/etc/ssl/private
        - $PWD/ssl:/etc/ssl/certs
    environment: 
        CRT: wordpress.crt
        KEY: wordpress.key
    ports: 
        - 33212:80
        - 8080:443
    links: 
        - wordpress
    restart: always
    networks: 
        - wp_network
networks:
    wp_network:
        name: wp_network
volumes: 
    wordpress:
        external: true
    mariadb:
        external: true
